"""Shared protocol constants for synchronous PS and Ring AllReduce."""

PROTOCOL_VERSION = "stage1.v1"
BIND_HOST = "127.0.0.1"
DEFAULT_MAX_FRAME = 64 * 1024 * 1024
DEFAULT_HEARTBEAT_INTERVAL_S = 1.0
DEFAULT_HEARTBEAT_TIMEOUT_S = 5.0
DEFAULT_RECONNECT_WAIT_S = 10.0
DEFAULT_REQUEST_TIMEOUT_S = 30.0
DEFAULT_STEP_TIMEOUT_S = 120.0
DEFAULT_CLEANUP_S = 5.0
DEFAULT_PS_RETAIN_ROUNDS = 1
DEFAULT_PS_DIGEST_ROUNDS = 8
DEFAULT_RING_DIGEST_STEPS = 4
OPTIMIZER_IMPL = "MyFlows.train.opt.Adam"
KNOWN_TASKS = ("synthetic", "mnist_mlp", "donkey_cnn", "donkey_resnet18")

STATUS_OK = "OK"
STATUS_WAITING = "WAITING"
STATUS_INVALID = "INVALID_MESSAGE"
STATUS_SCHEMA = "SCHEMA_MISMATCH"
STATUS_STALE = "STALE_VERSION"
STATUS_DUP = "DUPLICATE_CONFLICT"
STATUS_OFFLINE = "WORKER_OFFLINE"
STATUS_TIMEOUT = "TIMEOUT"
STATUS_ABORTED = "RUN_ABORTED"

LEGAL_MODES = {
    ("single", "none"),
    ("ps", "socket_json"),
    ("ps", "grpc_proto"),
    ("ring", "grpc_proto"),
}
